baseURL = 'https://matyisarihazasodik.hu/'
publishDir = 'public'
languageCode = 'hu-hu'
title = 'Matyi Sári házasodik'

[[menu.main]]
name = "Főoldal"
url = "/"
weight = 1

[[menu.main]]
name = "Program"
url = "/napirend"
weight = 2

[[menu.main]]
name = "Cím"
url = "/szallas"
weight = 3

[[menu.main]]
name = "Egyéb infók"
url = "/egyeb-infok"
weight = 4
