baseURL = 'https://matyisarihazasodik.hu/'
languageCode = 'hu-hu'
title = 'Bazinagy Káli Lagzi '

[[menu.main]]
name = "Főoldal"
url = "/"
weight = 1

[[menu.main]]
name = "Napirend"
url = "/napirend"
weight = 2

[[menu.main]]
name = "Szállás lehetősége"
url = "/szallas"
weight = 3

[[menu.main]]
name = "Egyéb infók"
url = "/egyeb-infok"
weight = 4
